### ISSUE TITLE
Отображение точек: фильтры, слои и т.д.

### ISSUE THREAD

**Issue by jekhor** [jekhor/wp-plugin-eurovelo-map#4]

**Comment by valoshca** [comment]
добавить checkboxы на типы кнопок. 

Названия этих checkboxов:
По идее для англоязычной карты они нужны на английском, для русскоязычной на русском.
Или совмещать в нахвание оба описания чтобы не хотелось по причине длины названия 
"место для палатки / place for tent"

добавить двуязычное отображение и на остальные checkboxы: "Валожынския гастинцы", слои.

**Comment by valoshca** [comment]
Состояние чекбоксов должно запоминаться при переключении между страницами

**Comment by valoshca** [comment]
Вынести считку точки для отображения в иной файл points.kml, который должен лежать в том же месте.
Таким образом, у нас будет 3 файла: 
eurovelo-routes.kml
давай его переименуем в ev2.kml
vh.kml
points.kml с общими точками для всех маршрутов

**Comment by jekhor** [comment]
Одна проблема — один тикет :)
Формулирую: загружать точки интереса из файла points.kml, при этом группировать однотипные точки в слои, которые можно включать-выключать.

Остальное — в отдельные задачи.
